DROP DATABASE IF EXISTS books;
CREATE DATABASE books;

USE books;

CREATE TABLE book (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE authors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  book_id INT NOT NULL,
  CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES book(id)
)